/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "goodbye cruel World!";
    }

    public String getsadGreeting() {
        return " ;(";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getsadGreeting());
        
        int series=0;
        int seriesodd = 0;
        int serieseven = 0;
        double geoseiro = 1.1;
        double geosum = 0;
        double geoseirio = 0.5;
        double geosuim = 0;
        byte x = 0;

        for (int number = 100; number>=0; number-=1){
            System.out.println ("NUMBERO "+number);
        }

        for (int i = 0; i<=100;i++){
            series+=i;
        }

        for (int i = 1; i<=99;i+=2){
            seriesodd+=i;
        }

        for (int i = 0; i<=100;i+=2){
            serieseven+=i;
        }

        for (int e = 1; e<=100; e++){
            System.out.println("X["+e+"]= "+geoseiro);
          geoseiro*=1.01; 
           geosum += geoseiro;
        } 

        for (int e = 1; e<=1000; e++){
            System.out.println("X["+e+"]= "+geoseirio);
          geosuim += geoseirio;
          geoseirio*=0.5; 
           
        } 



        System.out.println(series);
        System.out.println("odd sum = "+seriesodd);
        System.out.println("even sum = "+serieseven);
        System.out.println("geosum = "+geosum);
        System.out.println("geosum 2 = "+geosuim);
    }
}
